### ISSUE TITLE
너무 오래걸리는 계산 요청시 봇 사망

### ISSUE THREAD

**Issue by item4** [item4/yui#1]
`.= factorial(10000000000)`

**Comment by item4** [comment]
타임아웃을 넣어야!

**Comment by marnitto** [comment]
factorial 예제는 코드 구성상 Stack limit에 걸려서 처리되지 않았을 겁니다. rlimit을 주는 방법도 있지만, 이 문제는 factorial 구현을 다르게 하고, 혹시 모를 loop 처리를 위해서 timeout까지 넣으면 될 것 같습니다.
