### ISSUE TITLE
유이 월개 기능의 개명 투표

### ISSUE THREAD

**Issue by item4** [item4/yui#129]
현재 유이의 월개는 `월요일을 알리는 개새끼` 라는 이름을 사용중입니다. 해당 명칭은 동명의 트위터 컨셉계정에 착안한 것입니다. 하지만 `개새끼`라는 단어가 너무 노골적인 욕설로 보인다는 지적이 들어와서 개명을 고려하고 있습니다.

2018년 12월 4일 12시 0분 0초 (한국표준시)까지 본 이슈에 의견으르 담아 댓글을 남겨주세요.

### 선택지

- 1번: 지금 이름을 유지한다
- 2번: `개새끼` 대신 다른 단어를 사용한다. (`월월이`, `짖는개`, `멍멍이`, `멍뭉이`, `댕댕이` 등등)

### 선정 방법

1. 1번과 2번중 의견 수가 더 많은쪽을 택합니다.
2. 만약 2번이 더 많다면 2번에 투표하신분들이 제안하신 이름중에 맘에 드는걸 item4가 고릅니다.
3. 만약 1번이 더 많다면 `개새끼` 라는 단어가 곤란한 슬랙에서는 해당 기능을 종료합니다.

**Comment by item4** [comment]
일단 저부터. 저는 2번으로 가고 싶습니다. 제가 원하는 이름은 `월요일을 알리며 짖는 개` 입니다.

**Comment by kyunooh** [comment]
2. `월요일을 알리는 개새`하고 아이콘은 다음 친구들로
https://www.funshop.co.kr/goods/detail/42257?t=mm

**Comment by item4** [comment]
여러분, 댓글로 달린것만 인정됩니다. 따봉 눌러도 가산점 없어요..>!

**Comment by Jack-Valentine** [comment]
3. 스티븐로저스 로 하고 해일 하이드라 라고 말하는걸로

**Comment by kyunooh** [comment]
아니 그와중에 @Jack-Valentine 이분은 그렇게 PR을 많이 넣었는데 아직도 컨트리뷰터가 못된 게 실화입니까 ㅋㅋㅋ

**Comment by item4** [comment]
@kyunooh 권선징악

**Comment by dev-siot** [comment]
저는 1번으로 하고 곤란한 슬랙은 예외적으로 2번을 사용했으면 합니다.
짜증나는데 `개새끼` 라고도 못 하면 좀 그렇습니다.

**Comment by channprj** [comment]
저도 1번을 기본으로 하고 특정 슬랙에서는 2번이 나을 것 같습니다.

트위터 원조 월개도 ‘개새끼’ 라고 표현하네요.

**Comment by studioego** [comment]
2번 입니다.

**Comment by OuO** [comment]
2번이요~

**Comment by Nebu1eto** [comment]
1번 +1

**Comment by hunj** [comment]
2. `월요일을 알리는 개새` 와 인터넷 유머 합성 사진을 사용하는 정도가 무난할 것 같습니다.

**Comment by item4** [comment]
## 집계결과

1번 3표, 2번 5표로 2번으로 결정되었습니다.

## 수정 전략 안내

1. 앞으로 월개의 이름은 `월요일을 알리며 짖는 개` 로 변경됩니다.
2. 기존의 명칭 `월요일을 알리는 개새끼` 를 사용하고 싶은 슬랙이나 `개새`를 사용하고 싶은 슬랙을 위하여 월개의 이름과 프로필 사진을 설정 가능하게 변경합니다.
3. xnuk 팬클럽에서는 월개를 서비스하지 않습니다. (슬랙 관리자의 요청)

## 이슈의 닫힘에 대하여

본 댓글에서 정한 작업이 포함된 커밋이 push되면 이슈를 자동으로 닫겠습니다.

**Comment by KimChungHo** [comment]
요즘 '새끼'를 '쉑'으로 귀엽게 표현하는데 이건 어떨까요.
