### ISSUE TITLE
list/dict/set comprehension 버그

### ISSUE THREAD

**Issue by item4** [item4/yui#148]
scope 밖으로 변수가 새는 버그가 있습니다.

**Comment by hunj** [comment]
변수가 샌다는 게 어떤 의미인가요?

예를 들어:

```
lst = [1, 2, 3]

for x in lst:
    ...

print(x)  # => 3
```

이런 맥락인건가요?

**Comment by item4** [comment]
네 비슷합니다.

```py
x = 100
arr = [x for x in range(10)]
print(x) # must be 100, but yui has 9
```

**Comment by hunj** [comment]
https://docs.python.org/3/reference/compound_stmts.html#the-for-statement
> Names in the target list are not deleted when the loop is finished, but if the sequence is empty, they will not have been assigned to at all by the loop.

파이썬의 특징 중 하나인 것 같습니다. Iterator 를 다른 이름으로 사용하시거나 따로 함수로 빼는게 좋다고들 하네요.
